### ISSUE TITLE
关于最新的Wolong il2cpp文件

### ISSUE THREAD

**Issue by HDLSoCool** [It-Life/Deer_GameFramework_HuaTuo#1]
init_local_il2cpp_data.bat 批处理文件 双击无法克隆出Wolong il2cpp文件

**Comment by It-Life** [comment]
应该是github需要fq，开启fq看能否进入github页，能进去的话应该就可以克隆的

**Comment by It-Life** [comment]
还有就是init_local_il2cpp_data.bat 文件第一次需要打开修改里边Unity对应的安装目录，这个我抽时间在教程里补一下

**Comment by HDLSoCool** [comment]
我修改了bat里面的地址，克隆了LocalIl2CppData文件夹，但是打开项目提示未安装il2cpp

**Comment by It-Life** [comment]
检测一下BuildConfig.cs文件里的 LocalIl2CppDir字段路径是否正常
