### ISSUE TITLE
热更流程有没有支持版本回退的相关管理

### ISSUE THREAD

**Issue by youZhuang** [It-Life/Deer_GameFramework_HuaTuo#28]
比如当前已经有v1.0 v1.1 v1.2 三个版本的增量包,现在发现v1.2有问题了，想回到v1.1，有没有什么操作可以在不打新增量包的情况下让v1.2的玩家轻松回退到v1.1？

**Comment by It-Life** [comment]
版本管理在本地管理，或者你可以在下载资源前请求后端下载那个版本，在cdn做好版本文件夹管理
